Enable extension pausing when in "Recovery Mode"
wp-core-php/wordpress-develop pull request #6
Opened 2019-02-09 19:18 UTC by TimothyBJacobs

See [#46130](https://core.trac.wordpress.org/ticket/46130#comment:6) for an in-depth explanation.

2019-02-18 15:41 UTC, felixarntz reviewed
Great work so far! I pointed out a few concerns. Here are some more general observations and thoughts (partly also touched in inline comments):

* I think there should be a class for recovery mode functionality. `WP_Recovery_Mode` or something like that (should probably be a `final` class) - simply for the ability to better group functionality together and to make methods private that shouldn't be public.
* No files should be included anywhere but in code that a 100% surely terminates the request itself.
* We need to think about whether to use options or network options (in case we're in a multisite that's relevant). I think network options certainly make sense for the fallback key and salt that just replace a constant - for the rest, that's worth discussing.
* I don't think we need the concept of protected endpoints any longer. If in recovery mode, pause extensions - if not, don't. IMO there's no need for this additional complexity, i.e. the `is_protected_endpoint()` should be dropped completely in favor of `wp_is_recovery_mode()`.

+1 on using custom code for the hashing etc. - since we can't use the pluggable functions in these circumstances, that's a fine approach I'd say.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +							if ( empty( $error['wp_is_protected'] ) ) {
I don't think we need to differentiate here. I think only errors that happen during recovery mode should be stored, and only the latest one per extension.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			if ( $this->store_error( $error ) && wp_is_recovery_mode() ) {
I think the two conditions should be ordered the other way around, if we only store errors in recovery mode.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +	$error['wp_is_protected'] = is_protected_endpoint();
Per the above, this shouldn't be necessary.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/pluggable.php
> +		clear_recovery_mode_cookie();
Can we maybe hook into an action instead? This could be problematic since the function might be overridden. On the other hand, we might not even want to clear that cookie here, as it is not tied to a logged-in user anyway.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-login.php
> +if ( ! in_array( $action, array( 'postpass', 'logout', 'lostpassword', 'retrievepassword', 'resetpass', 'rp', 'register', 'login', 'confirmaction', 'begun_recovery_mode' ), true ) && false === has_fi
I suggest using `entered_recovery_mode` instead.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> + * @since 5.1.0
Version numbers can be updated to 5.2.0. :)

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +		require_once ABSPATH . WPINC . '/pluggable.php';
Such inclusions should happen in the same function that also dies at the end of its execution, to make sure it never happens at a point when it shouldn't.

I generally suggest adding a class for the recovery mode functionality since it's quite complex and several functions would better be private/protected.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +	do_action( 'generate_recovery_mode_key', $key );
Do we need this action?

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +	update_site_option( 'recovery_key', array(
What was the reasoning behind using `*_site_option()` instead of `*_option()`?

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +	$record = get_site_option( 'recovery_key' );
See above.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +		require_once ABSPATH . WPINC . '/pluggable.php';
See above, such an inclusion shouldn't happen in a function that does not terminate the request and is publicly callable.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +	if ( ! defined( 'AUTH_KEY' ) || AUTH_KEY === 'put your unique phrase here' ) {
Use Yoda condition you must. 😛

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +				require_once ABSPATH . WPINC . '/pluggable.php';
See above.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +				require_once ABSPATH . WPINC . '/pluggable.php';
See above.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +		require_once ABSPATH . WPINC . '/pluggable.php';
See above.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +			return new WP_Error( 'no_cookie' );
Missing error message.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +	if ( isset( $_GET['action'], $_GET['rm_key'] ) && 'begin_recovery_mode' === $_GET['action'] ) {
I suggest using `enter_recovery_mode`.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +		$message = '<script type="application/javascript">window.location = \'' . esc_js( $url ) . '\';</script>';
I read your comment on why you did that, but I think we should further look into why redirecting via PHP doesn't work. The approach here seems weird.

2019-02-18 15:41 UTC, felixarntz commented on src/wp-includes/load.php
> +	), wp_login_url() );
This violates WP Coding Standards :)

2019-02-18 16:03 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +	update_site_option( 'recovery_key', array(
This matches the behavior in `wp_salt()`

2019-02-18 16:05 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +	if ( isset( $_GET['action'], $_GET['rm_key'] ) && 'begin_recovery_mode' === $_GET['action'] ) {
Works for me

2019-02-18 16:06 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +		$message = '<script type="application/javascript">window.location = \'' . esc_js( $url ) . '\';</script>';
Yeah, I'm not sure what was going on there. Setting the cookie and redirect should work, that's how `wp-login.php` happens. So I was probably seeing some other behavior.

2019-02-18 16:06 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +	), wp_login_url() );
Sorry, how are we supposed to format that now?

2019-02-18 16:09 UTC, TimothyBJacobs commented on src/wp-includes/pluggable.php
> +		clear_recovery_mode_cookie();
Can do. I lean towards clearing it since recovery mode is something security sensitive, even if it isn't actually authenticating the user.

2019-02-18 16:12 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +		require_once ABSPATH . WPINC . '/pluggable.php';
Agreed.

2019-02-18 16:12 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +	do_action( 'generate_recovery_mode_key', $key );
We should probably do a pass on filters/actions after everything else is ready. I think extension pieces are important here for hosts that might want to handle things differently. I think its probably too complex for replacing wholesale via a drop-in.

2019-02-18 17:25 UTC, swissspidy commented on src/wp-includes/load.php
> +	), wp_login_url() );
@TimothyBJacobs if a function call is multi-line, each parameter should start on a new line:

```php
$url = add_query_arg(
	array(
		'action' => 'begin_recovery_mode',
		'rm_key' => $key,
	),
	wp_login_url()
);
```

2019-02-18 17:27 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +	), wp_login_url() );
Thank you @swissspidy! will update

2019-02-18 17:29 UTC, swissspidy commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +								$error_message = __( 'The plugin caused an error in the <strong>admin backend</strong> of type %1$s in line %2$s of the file %3$s. Error message: %4$s' );
FYI in WordPress we use the noun `back end` instead of `backend`, see https://make.wordpress.org/core/handbook/best-practices/spelling/.

Also, `admin backend` is a bit of a pleonasm. I'd either use `admin` or `back end`, not both.

2019-02-21 05:35 UTC, TimothyBJacobs commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +								$error_message = __( 'The plugin caused an error in the <strong>admin backend</strong> of type %1$s in line %2$s of the file %3$s. Error message: %4$s' );
Updated

2019-02-21 05:37 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +		require_once ABSPATH . WPINC . '/pluggable.php';
Moved to a class.

2019-03-04 16:01 UTC, TimothyBJacobs commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +							if ( empty( $error['wp_is_protected'] ) ) {
This is no longer differentiated it. We store all errors in recovery mode and only email for errors in protected endpoints.

2019-03-18 13:04 UTC, TimothyBJacobs commented
User Flow & Technical Doc: https://docs.google.com/document/d/1XWQghXj0p0X8GF-Byuv4vfPQG0Rs0XoVfOepVjiMkfM/edit
From Slack: 

I do think we are in a good place extensibility wise to be able to support a user email specific flow in 5.3 with our current framework and IMO could be implemented as a drop-in with some minor changes. The main thing being an `exit_recovery_mode()` method of some kind.

I think that putting an exit mode in the admin bar makes sense. I think it’d be quickest to add the underlying technical support for exiting recovery mode, like a method, in the patch before commit and then worry about that specific UI shortly thereafter.
From a thread in #core-phpToday at 8:55 AMView reply

Looking at a specific of the technical document, I don’t think we should overload the `is_active()` method on the controller. That will make it harder to support more advanced recovery mode procedures in the future. I’m fairly confident that just having a session ID will be enough to support per-user recovery mode, ie we don’t actually need to provide the user ID. If we do find that we need actual data about the user, then I think that’d be better off by implementing a specific `WP_User_Specific_Recovery_Mode_Controller` interface with a `get_user_id(): int` method ( or something similar ) that way we can properly handle recovery mode controllers that are site wide, like the current controller.
I also think we should keep the separation of concerns with the additional helper classes, instead of moving many of these to private methods. Moving them into separate classes allows for better unit testability, see `Tests_Recovery_Mode`, eases understanding by grouping similar functionality together, and makes it substantially easier for drop-ins or other customer recovery mode controllers to work. This will give them the helper libraries they need so they aren’t forced to reinvent the wheel or copy parts of the original controller implementation .

2019-03-18 13:12 UTC, felixarntz commented
> Looking at a specific of the technical document, I don’t think we should overload the `is_active()` method on the controller. That will make it harder to support more advanced recovery mode procedures in the future. I’m fairly confident that just having a session ID will be enough to support per-user recovery mode, ie we don’t actually need to provide the user ID.

Given the current approach, this completely makes sense. Let's have a `is_active()` and separate `get_session_id()` method. Later, we could potentially store a session ID in user meta to associate them, if needed.

> I also think we should keep the separation of concerns with the additional helper classes, instead of moving many of these to private methods.

Yes. The reason I made them private methods in the doc was mostly to have a better understanding when reading about them - I see it as a starting point to abstract from further. The multiple classes approach is better organized, but a bit harder to grasp at first glance.

2019-03-18 13:15 UTC, nerrad commented
For first iteration (release in 5.2) I think this should be disabled for WordPress multisite.  There's ux/ui workflows that need to be considered in a multisite environment and typically those working with multisite have a better handle on dealing with php/plugin upgrades etc. so the urgency for these protections in that environment isn't as great.

2019-03-18 14:25 UTC, felixarntz requested changes
I did a more thorough review and pointed out some details. Most of it is looking good.

A few more general things:
* Let's keep the `WP_Fatal_Error_Handler` class as generic as it can be. Storing errors, redirecting, etc. already ties in with recovery mode and how we envision it, so these things should be covered by the recovery mode controller. The only connection should be the fatal error handler calling the `handle_fatal_error()` method.
* Let's be conservative and not expose too much code through functions that we only call in one location. We use class structures here, and the feature is in a first iteration, so we don't want to expose too much for outside usage here.
* The same applies to overriding. People can override the fatal error handler, and thus technically already have the ability to override in whichever way they want. For the first iteration, let's not get more granular, i.e. not allow to override the recovery mode handler specifically. In `is_recovery_mode_active()`, we can check a constant that MU plugins can define - that allows for customizing that bit, while not restricting us in what we can do to our class infrastructure later. We don't want to corner ourselves.
* Function/method descriptions in doc-blocks should start with a third-person verb rather than infinitive. :)

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +					}
This clause should be removed, as we don't act on network-active plugins.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +				}
The check in this clause needs a `! $screen->in_admin( 'network' )` check.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +					}
This clause should be removed.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +					}
This clause should be removed.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +					}
This clause should be removed.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +		$paused = is_plugin_paused( $plugin_file );
This should first check `! $screen->in_admin( 'network' )`.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/plugin.php
> +		'recovery-mode-controller.php' => array( __( 'Custom recovery mode controller.' ), true ), // auto on error
Let's not support a `recovery-mode-controller.php` drop-in for now. This is much more complicated functionality in an early state, and furthermore it is more applicable to be modified by MU plugins. Drop-ins should only be added for things that need to run very early.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/plugin.php
> +	if ( ! is_plugin_active( $plugin ) && ! is_plugin_active_for_network( $plugin ) ) {
The `! is_plugin_active_for_network( $plugin )` should be removed, we don't cover network-active plugins.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/plugin.php
> +function count_paused_plugin_sites_for_network( $plugin ) {
This function should be removed.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/plugin.php
> +	if ( ! current_user_can( 'deactivate_plugins' ) ) {
Let's check `resume_plugins` instead.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/theme.php
> +function count_paused_theme_sites_for_network( $theme ) {
This function should be removed.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/theme.php
> +	if ( ! current_user_can( 'switch_themes' ) ) {
Let's check `resume_themes` instead.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/plugins.php
> +			if ( is_multisite() && ! is_network_admin() && is_network_only_plugin( $plugin ) ) {
Let's change this clause to `is_multisite() && is_network_admin()` and put it at the beginning of the `case 'resume'`, to ensure this doesn't do anything in the network admin.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/plugins.php
> +			$result = resume_plugin( $plugin, self_admin_url( 'plugins.php?error=resuming' ), is_network_admin() );
Do not pass the third parameter here.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/themes.php
> +		if ( ! current_user_can( 'resume_themes' ) ) {
This should be `! current_user_can( 'resume_theme', $_GET['stylesheet'] )`.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/capabilities.php
> +			break;
There should also be a similar clause for `resume_theme`, resolving to `resume_themes`.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			}
Let's move this entire handling into `wp_recovery_mode()->handle_error()`, so that instead of the if-else the code only calls that method here. The method should return a boolean on whether it could successfully handle the error (false if caused by core/drop-in/MU-plugin/network-plugin, or if storing it failed due to an internal error).

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		if ( ! wp_should_handle_error( $error ) ) {
Let's remove this function and move it to an internal method, since it's only used here, and we shouldn't expose more than necessary.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-fatal-error-handler.php
> +	protected function store_error( $error ) {
This should be removed from here, the recovery mode controller should take care of this.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-fatal-error-handler.php
> +	protected function redirect_protected() {
This should be removed from here, the recovery mode controller should take care of this.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +	public function record( $type, $extension, $error ) {
Rename this to `set()`.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +	public function forget( $type, $extension ) {
Rename this to `delete()`.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +class WP_Paused_Extensions_Storage {
What was the reason for changing the class from how it worked in https://github.com/wp-core-php/wordpress-develop/pull/5/files#diff-a08d55fe0e259e54b08e51ef2dea7a7c? I think it's cleaner having separate instances for plugins and themes - as they can theoretically share names. Let's have two distinct options for plugins/themes.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +	public function get_site_meta_query_clause( $type, $extension ) {
Let's remove this method for now, as we don't need it (yet).

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +	private function get_site_meta_key( $type, $extension ) {
Instead of having this method, both the option name and site meta key name parts that depend on whether plugin or theme should:
* either be passed via the constructor (with core taking care of this instantiation somewhere)
* or be defined in child classes (making this an abstract class and then having `WP_Paused_Plugins_Storage` and `WP_Paused_Themes_Storage` extending this)

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-controller.php
> +	public function is_recovery_mode_active();
I think this should be shortened to `is_active()`.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-controller.php
> +	public function get_recovery_mode_session_id();
I think this should be shortened to `get_session_id()`.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +final class WP_Recovery_Mode_Cookie_Service {
This class is missing quite a few docs. File, class, properties, methods should all have descriptions and `since` annotations.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-controller.php
> +interface WP_Recovery_Mode_Controller {
As much as _I_ think interfaces are a good idea, let's not do this right now. Similar to the `WP_Fatal_Error_Handler`, let's make this here a class with the default implementation (migrating the code from `WP_Recovery_Mode_Email_Controller` into here.

Introducing interfaces doesn't have a best practice yet (also in terms of coding standards, where the current `class-` prefix wouldn't make sense). It would be good to explore this in the near future, but not now for this feature, given the time constraints.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +final class WP_Recovery_Mode_Email_Controller implements WP_Recovery_Mode_Controller {
As mentioned above, let's make this the `WP_Recovery_Mode_Controller` class and ditch the interface.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +	private $session_id = false;
All these properties need a description and a `since` annotation.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +	public function __construct( WP_Recovery_Mode_Cookie_Service $cookies, WP_Recovery_Mode_Key_Service $keys ) {
Similarly to ditching the interface, let's ditch dependency injection here. We can always add that back later. Let's have the constructor instantiate these classes in the properties instead.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +		}
As mentioned above, this should do a few more things:
* return a boolean to indicate success/failure
* take over some code from `wp_record_extension_error()` to check where the error is coming from
    * if from core/drop-in/MU-plugin/network plugin, return false
    * otherwise, try storing the error (if that fails, return false)
    * of course this doesn't all need to go in one method, could also become separate protected methods
* if on a protected endpoint and storing the error was successful, take care of redirecting

This moves responsibility for all these tasks to the recovery mode controller, rather than having that responsibility shattered across several core areas.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +		return apply_filters( 'recovery_mode_email_rate_limit', 4 * HOUR_IN_SECONDS );
Just curious, why 4? We previously discussed 1 hour as the default.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +			update_site_option( 'recovery_mode_email_last_sent', time() );
I think we should update the option before sending the email, and bail if that call was unsuccessful: If we can't store when the email was last sent for whatever internal bug, it would effectively disable the rate limit.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +	private function get_error_details( $error ) {
Can we possibly merge some of this with code from `wp_get_plugin_error_description()`? There appears to be quite some overlap. Maybe `wp_get_plugin_error_description()` should also get a more generic name (not include "plugin").

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +			$cause = wp_sprintf( _n( 'This may be caused by the %l plugin.', 'This may be caused by the %l plugins.', count( $names ) ), $names );
Even though this can technically be the case, let's not use "may" here, as it will just cause unnecessary uncertainty in most cases.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +			$cause = sprintf( __( 'This may be caused by the %s theme.' ), $name );
Similarly, let's not use "may" here.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +final class WP_Recovery_Mode_Key_Service {
This needs file and class docs.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +			require_once ABSPATH . WPINC . '/pluggable.php';
There shouldn't be file inclusions anywhere unless the same piece of code also ensures that execution stops afterwards (with `exit` or `die()`).

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +			require_once ABSPATH . WPINC . '/class-phpass.php';
Same here. Such file inclusions should happen in a more high level class that also ensures the process terminates after the recovery code has run. This ensures we don't accidentally miss a case and therefore run into double required file / pluggable already existing issues.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +			require_once ABSPATH . WPINC . '/pluggable.php';
Same here.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +function wp_record_extension_error( $error ) {
Let's ditch this function. The respective code should be moved to the recovery mode controller. This isn't a function anybody should easily be able to call, and not having it as a function makes that less likely.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +function wp_paused_extensions() {
Let's split that into `wp_paused_plugins()` and `wp_paused_themes()`, similar to how it was originally.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +function wp_get_extension_for_error( $error ) {
Similar to `wp_record_extension_error()`, this should be removed and the functionality should become part of the recovery mode controller.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-admin/includes/plugin.php
> +function resume_plugin( $plugin, $redirect = '', $network_wide = false ) {
Let's ditch the `$network_wide` parameter.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +function wp_forget_extension_error( $type, $extension, $network_wide = false ) {
Let's ditch this function as well. We don't need a `$network_wide` parameter, and the rest of the functionality can easily accounted for by just using the paused extensions storage.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +function wp_should_handle_error( $error ) {
This should also be ditched and moved to the recovery mode handler.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +		}
As mentioned above, let's not support a drop-in here.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +		$wp_recovery_mode = apply_filters( 'wp_recovery_mode_controller', $wp_recovery_mode );
I think in the first iteration we shouldn't make this overrideable at all. It can introduce significant roadblocks for the future. Let's remove for now and reconsider for v2.

2019-03-18 14:25 UTC, felixarntz commented on tests/phpunit/tests/user/capabilities.php
> +			$expected['resume_plugin'],
Related to the suggestion to introduce `resume_theme`, that capability needs to be included here as well then.

2019-03-18 14:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +	public function run() {
Let's add a check for a constant here:
```php
if ( defined( 'WP_RECOVERY_MODE_SESSION_ID' ) {
    $this->is_active = true;
    $this->session_id = WP_RECOVERY_MODE_SESSION_ID;
    return;
}
```

This allows people to short-circuit everything while not tying in too much with our early class infrastructure.

2019-03-18 14:43 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +class WP_Paused_Extensions_Storage {
You suggested consolidating it into one option :)
https://wordpress.slack.com/archives/C60K3MP2Q/p1550509401260900

2019-03-18 14:46 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +		return apply_filters( 'recovery_mode_email_rate_limit', 4 * HOUR_IN_SECONDS );
This was discussed in the Thursday meeting: https://wordpress.slack.com/archives/C60K3MP2Q/p1550761315015300

I'm fine with either.

2019-03-18 14:53 UTC, TimothyBJacobs commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +					}
Removed.

2019-03-18 14:54 UTC, TimothyBJacobs commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +				}
Added

2019-03-18 14:54 UTC, TimothyBJacobs commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +					}
Removed

2019-03-18 14:54 UTC, TimothyBJacobs commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +					}
Removed

2019-03-18 14:54 UTC, TimothyBJacobs commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +		$paused = is_plugin_paused( $plugin_file );
Added a check.

2019-03-18 14:55 UTC, TimothyBJacobs commented on src/wp-admin/includes/class-wp-plugins-list-table.php
> +					}
Removed

2019-03-18 14:55 UTC, TimothyBJacobs commented on src/wp-admin/includes/plugin.php
> +	if ( ! is_plugin_active( $plugin ) && ! is_plugin_active_for_network( $plugin ) ) {
Removed

2019-03-18 14:55 UTC, TimothyBJacobs commented on src/wp-admin/includes/plugin.php
> +function count_paused_plugin_sites_for_network( $plugin ) {
Removed

2019-03-18 14:55 UTC, TimothyBJacobs commented on src/wp-admin/includes/plugin.php
> +	if ( ! current_user_can( 'deactivate_plugins' ) ) {
Changed

2019-03-18 14:55 UTC, TimothyBJacobs commented on src/wp-admin/includes/theme.php
> +function count_paused_theme_sites_for_network( $theme ) {
Removed

2019-03-18 14:55 UTC, TimothyBJacobs commented on src/wp-admin/plugins.php
> +			if ( is_multisite() && ! is_network_admin() && is_network_only_plugin( $plugin ) ) {
Changed.

2019-03-18 14:55 UTC, TimothyBJacobs commented on src/wp-admin/plugins.php
> +			$result = resume_plugin( $plugin, self_admin_url( 'plugins.php?error=resuming' ), is_network_admin() );
Removed.

2019-03-18 14:56 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +	public function get_site_meta_query_clause( $type, $extension ) {
Removed.

2019-03-18 14:57 UTC, TimothyBJacobs commented on src/wp-admin/includes/plugin.php
> +function resume_plugin( $plugin, $redirect = '', $network_wide = false ) {
Removed.

2019-03-18 14:57 UTC, TimothyBJacobs commented on src/wp-includes/error-protection.php
> +function wp_forget_extension_error( $type, $extension, $network_wide = false ) {
Removed.

2019-03-18 15:02 UTC, TimothyBJacobs commented on tests/phpunit/tests/user/capabilities.php
> +			$expected['resume_plugin'],
Added

2019-03-18 15:05 UTC, TimothyBJacobs commented on src/wp-includes/capabilities.php
> +			break;
Added.

2019-03-18 15:06 UTC, TimothyBJacobs commented on src/wp-admin/themes.php
> +		if ( ! current_user_can( 'resume_themes' ) ) {
Changed

2019-03-18 15:06 UTC, TimothyBJacobs commented on src/wp-admin/includes/theme.php
> +	if ( ! current_user_can( 'switch_themes' ) ) {
Changed

2019-03-18 15:42 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		if ( ! wp_should_handle_error( $error ) ) {
Moved.

2019-03-18 15:42 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +	public function record( $type, $extension, $error ) {
Renamed.

2019-03-18 15:42 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +	public function forget( $type, $extension ) {
Renamed

2019-03-18 15:42 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +class WP_Paused_Extensions_Storage {
Changed into two storage instances that use the same option backend.

2019-03-18 15:42 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +	private function get_site_meta_key( $type, $extension ) {
Dropped.

2019-03-18 15:44 UTC, TimothyBJacobs commented on src/wp-includes/error-protection.php
> +function wp_record_extension_error( $error ) {
Removed.

2019-03-18 15:44 UTC, TimothyBJacobs commented on src/wp-includes/error-protection.php
> +function wp_paused_extensions() {
Resplit.

2019-03-18 15:44 UTC, TimothyBJacobs commented on src/wp-includes/error-protection.php
> +function wp_should_handle_error( $error ) {
Moved out of the global namespace. In a different class temporarilyish.

2019-03-18 16:44 UTC, felixarntz commented
Just taking a note here that we should wrap the calls in `wp-settings.php` into a `! is_multisite()`, as the feature will be disabled for multisite in v1.

2019-03-18 18:15 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +			$cause = wp_sprintf( _n( 'This may be caused by the %l plugin.', 'This may be caused by the %l plugins.', count( $names ) ), $names );
Going to leave this for the specific [copy review ticket](https://github.com/WordPress/servehappy/issues/40).

2019-03-18 18:21 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +		return apply_filters( 'recovery_mode_email_rate_limit', 4 * HOUR_IN_SECONDS );
Leaving as 4 hours and resetting the rate limit when exiting recovery mode: https://wordpress.slack.com/archives/C60K3MP2Q/p1552928344557400

2019-03-18 18:22 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +	private function get_error_details( $error ) {
Merged and stripped tags in the email version.

2019-03-18 18:23 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +		}
Resolved. This returns `WP_Error` or `die`s I couldn't find a case where it'd return true.

2019-03-18 18:24 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			}
Moved.

2019-03-18 18:34 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +	public function run() {
Added.

2019-03-18 18:35 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +			require_once ABSPATH . WPINC . '/pluggable.php';
Moved to `WP_Recovery_Mode::handle_error()`. I think this is the highest it could reasonably go, the next level would be `WP_Fatal_Error_Handler` itself, but I think that's overkill.

2019-03-18 18:42 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +			update_site_option( 'recovery_mode_email_last_sent', time() );
Changed.

2019-03-18 18:43 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +	public function __construct( WP_Recovery_Mode_Cookie_Service $cookies, WP_Recovery_Mode_Key_Service $keys ) {
Removed.

2019-03-18 18:43 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +	private $session_id = false;
Added

2019-03-18 18:43 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-controller.php
> +interface WP_Recovery_Mode_Controller {
Removed interface support.

2019-03-18 18:44 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +final class WP_Recovery_Mode_Cookie_Service {
Added docs.

2019-03-18 18:44 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-controller.php
> +	public function get_recovery_mode_session_id();
Shortened

2019-03-18 18:44 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-controller.php
> +	public function is_recovery_mode_active();
Shortened.

2019-03-18 19:42 UTC, TimothyBJacobs commented on src/wp-includes/error-protection.php
> +function wp_get_extension_for_error( $error ) {
Moved.

2019-03-18 19:43 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-controller.php
> +final class WP_Recovery_Mode_Email_Controller implements WP_Recovery_Mode_Controller {
Removed.

2019-03-18 19:52 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +			require_once ABSPATH . WPINC . '/class-phpass.php';
I don't think this is necessary for `phpass`. `require_once ABSPATH . WPINC . '/class-phpass.php'` is a pattern throughout core because it is only loaded when necessary.

2019-03-19 09:58 UTC, felixarntz requested changes
This is getting close. A few outstanding comments.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode.php
> +		$this->cookies = new WP_Recovery_Mode_Cookie_Service();
The fact you instantiate `WP_Recovery_Mode_Cookie_Service` both here and in `WP_Recovery_Mode_Email_Link` tells me there's something wrong.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +final class WP_Recovery_Mode_Email_Link {
This class should be simplified to only be responsible for the actual email sending. The recovery link handling is agnostic of how the user obtains that link. I think it should be moved to `WP_Recovery_Mode` or a new `WP_Recovery_Mode_Link`.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +		$this->cookies = new WP_Recovery_Mode_Cookie_Service();
This class shouldn't need to worry about the recovery cookie.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +	public function handle_begin_link() {
This method should be moved elsewhere.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +	private function get_recovery_mode_begin_url( $key ) {
This method should be moved elsewhere.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +	private function get_link_valid_for_interval() {
This method should be moved elsewhere.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +			$cause = sprintf( __( 'This may be caused by the %s theme.' ), $name );
As mentioned before, I'd refrain from using "may" here. Let's just say "This was caused by ...".

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/error-protection.php
> +	$error_message = __( 'The plugin caused an error of type %1$s in line %2$s of the file %3$s. Error message: %4$s' );
This is no longer plugin-specific. Let's rephrase to "An error of type %1$s was caused in line %2$s of the file %3$s."

In the areas where this function is used, it's obvious by the context which plugin or theme caused it anyway.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			wp_recovery_mode()->handle_error( $error );
Let's wrap this in a `! is_multisite()` clause, just to be sure.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-settings.php
> +wp_register_fatal_error_handler();
We need to discuss whether this should also be excluded if `! is_multisite()`.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-settings.php
> +require( ABSPATH . WPINC . '/class-wp-recovery-mode.php' );
Looking at these classes and the other observations, I suggest we do the following:
* Introduce `WP_Recovery_Mode_Link_Service`, moving most code that is currently in `WP_Recovery_Mode_Email_Link` there. The `WP_Recovery_Mode_Key_Service` instance should also be moved there, as the email handler doesn't need to know about it. The `WP_Recovery_Mode_Email_Link` instance should be controlled by `WP_Recovery_Mode`.
* Rename `WP_Recovery_Mode_Email_Link` to `WP_Recovery_Mode_Email_Service`.
* We need to allow `WP_Recovery_Mode_Email_Service` to get a recovery link, for inclusion in the email. I suggest we add a utility function `wp_get_recovery_mode_link()` that wraps the respective method in `WP_Recovery_Mode_Link_Service` (accessed via `wp_recovery_mode()`). The email class can then call this function. For that part I'd argue a wrapper function is useful so that developers can easily work with recovery links, e.g. for implementing an alternative way to retrieve it. The alternative to that function would be dependency injection, but as mentioned before I'd rather not add constructor parameters in this early stage of the API.

2019-03-19 09:58 UTC, felixarntz commented on src/wp-settings.php
> +// Handle users requesting a recovery mode link and initiating recovery mode.
Wrong indentation :)

2019-03-19 09:58 UTC, felixarntz commented on tests/phpunit/tests/recovery-mode.php
> +class Tests_Recovery_Mode extends WP_UnitTestCase {
Can you add `@group error-protection` to the class doc?

2019-03-19 09:58 UTC, felixarntz commented on tests/phpunit/tests/recovery-mode.php
> +	public function test_generate_and_store_returns_recovery_key() {
Can you add `@ticket 46130` to all test method annotations?

2019-03-19 18:08 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +	private function get_link_valid_for_interval() {
Moved.

2019-03-19 18:08 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +			$cause = sprintf( __( 'This may be caused by the %s theme.' ), $name );
Updated.

2019-03-19 18:08 UTC, TimothyBJacobs commented on src/wp-includes/error-protection.php
> +	$error_message = __( 'The plugin caused an error of type %1$s in line %2$s of the file %3$s. Error message: %4$s' );
Updated.

2019-03-19 18:09 UTC, TimothyBJacobs commented on src/wp-settings.php
> +require( ABSPATH . WPINC . '/class-wp-recovery-mode.php' );
I followed that path mostly, but passed the link service as a method parameter to avoid introducing a global function that back references the recovery mode class that is calling the function in the first place.

2019-03-19 18:09 UTC, TimothyBJacobs commented on src/wp-settings.php
> +// Handle users requesting a recovery mode link and initiating recovery mode.
Fixed.

2019-03-19 18:09 UTC, TimothyBJacobs commented on tests/phpunit/tests/recovery-mode.php
> +class Tests_Recovery_Mode extends WP_UnitTestCase {
Added

2019-03-19 18:09 UTC, TimothyBJacobs commented on tests/phpunit/tests/recovery-mode.php
> +	public function test_generate_and_store_returns_recovery_key() {
Added

2019-03-19 18:09 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			wp_recovery_mode()->handle_error( $error );
Added

2019-03-19 18:09 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +	private function get_recovery_mode_begin_url( $key ) {
Moved.

2019-03-19 18:10 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +	public function handle_begin_link() {
Moved.

2019-03-19 18:10 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +		$this->cookies = new WP_Recovery_Mode_Cookie_Service();
Removed both services.

2019-03-19 18:10 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-link.php
> +final class WP_Recovery_Mode_Email_Link {
Extracted to a separate link service.

2019-03-19 18:24 UTC, spacedmonkey commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			if ( ! is_multisite() ) {
Why is this disabled on multisite?

2019-03-19 18:26 UTC, spacedmonkey commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		if ( defined( 'WP_EXECUTION_SUCCEEDED' ) && WP_EXECUTION_SUCCEEDED ) {
I have posted my thoughts on this [here](https://core.trac.wordpress.org/ticket/45989#comment:25). I don't like the `WP_EXECUTION_SUCCEEDED` constant.

2019-03-19 18:26 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			if ( ! is_multisite() ) {
From the summary of the meeting in slack: https://wordpress.slack.com/archives/C60K3MP2Q/p1552927814544600

> We're not going to support multisite in v1.

2019-03-19 20:33 UTC, spacedmonkey requested changes
That is my code review for now.

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		$error_types_to_handle = array(
Should this have a filter?

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		wp_die( $message, '', $args );
Should this pass a `WP_Error` here? So the code in `wp_die` json handler shows a code, so easier to find where the error comes from.

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$paused_extensions = (array) get_option( $this->option_name, array() );
Maybe we could use the function `__get_option` here. `get_option` function has a number of filters on it, that could break or change how this received from the database. `__get_option` is a clean function that just calls the database , aviods caches and filters.

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$paused_extensions = (array) get_option( $this->option_name, array() );
Long term do we want to store this data in blog meta. Should we do this now, as it maybe hard to change later.

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$paused_extensions = (array) get_option( $this->option_name, array() );
Should we use `register_setting` so we can see this setting in the api and setup the default.

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +final class WP_Recovery_Mode_Email_Service {
Why is does this need to be final?

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +	public function maybe_send_recovery_mode_email( WP_Recovery_Mode_Link_Service $link_service, $rate_limit, $error, $extension ) {
Is this supported in 5.2? `WP_Recovery_Mode_Link_Service $link_service`

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		if ( ! $last_sent || time() > $last_sent + $rate_limit ) {
Other parts of core use transients as a lock here. See `_get_cron_lock`. Which is not a bad pattern. It would be self clearing in the database.

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		$blogname = wp_specialchars_decode( get_option( 'blogname' ), ENT_QUOTES );
Shouldn't we use `get_bloginfo` here?

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +		update_site_option( 'recovery_key', array(
Why would you want this stored at network level if multisite is enabled.

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-admin/plugins.php
> +			if ( is_multisite() && is_network_admin() ) {
Why is this disabled?

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/admin-bar.php
> +				'title' => __( 'Exit Recovery Mode' )
Can we better explain what this button does somehow? Can we highlight this button

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-fatal-error-handler.php
> +
Should this work like `db-error.php`, this calls `die()` after the file is included.

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +				return new WP_Error( 'no_cookie' );
Should this have a message?

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +			$auth_key = get_site_option( 'recovery_mode_auth_key' );
Why is this stored at network level?

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +			$auth_salt = get_site_option( 'recovery_mode_auth_salt' );
Why is this stored at network level?

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode.php
> +		if ( ! function_exists( 'wp_redirect' ) ) {
Check for `wp_safe_redirect`

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/error-protection.php
> +	$enabled = ! defined( 'WP_DISABLE_FATAL_ERROR_HANDLER' ) || ! WP_DISABLE_FATAL_ERROR_HANDLER;
Love this :+1:

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-includes/load.php
> +	// Protect login pages.
Return in this function makes the filter useless here.
It should be more like this 
```
$protected = false;
if ( isset( $GLOBALS['pagenow'] ) && 'wp-login.php' === $GLOBALS['pagenow'] ) {
	$protected = true;
}
return (bool) apply_filters( 'is_protected_endpoint', $protected );

2019-03-19 20:33 UTC, spacedmonkey commented on src/wp-settings.php
> +if ( ! is_multisite() ) {
We need to discuss this

2019-03-20 04:22 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		$error_types_to_handle = array(
I think this is worthy of a filter. What say you @felixarntz.

2019-03-20 04:28 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		wp_die( $message, '', $args );
That makes sense to me. Adjusted to a WP_Error with code `internal_server_error`.

2019-03-20 04:39 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$paused_extensions = (array) get_option( $this->option_name, array() );
> Maybe we could use the function __get_option here.
I'm not sure whether `__get_option` makes sense or not. Currently it's private to `upgrade.php`. Not sure what the ramifications are of using it here.

> Long term do we want to store this data in blog meta. 
Yes, I think we'd want to use sitemeta for multisite. That was what the original extension storage used. But since we aren't supporting multisite at all the moment, we shouldn't run into any upgrade issues when we add it in 5.3.

> Should we use register_setting so we can see this setting in the api and setup the default.
The option name is dynamic so I don't think it'd be helpful. If we wanted to expose this in the REST API, I think we'd need a different strategy. Not sure how useful it'd be in a REST context though without plugin/theme management APIs.

2019-03-20 04:39 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +final class WP_Recovery_Mode_Email_Service {
I think for 5.2 we want to keep the API as closed as possible so we are more free to make changes in 5.3

2019-03-20 04:41 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +	public function maybe_send_recovery_mode_email( WP_Recovery_Mode_Link_Service $link_service, $rate_limit, $error, $extension ) {
Yes: https://3v4l.org/SiKBC

2019-03-20 04:44 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		if ( ! $last_sent || time() > $last_sent + $rate_limit ) {
I'm not necessarily opposed to a transient here. We can't rely on the transient to be there for the entire TTL though. Is that a problem? It'd also limit the utility of the rate limit being filterable since it'd have to wait at least a cycle to become effective ( we can't change the TTL after the transient has already been set ).

2019-03-20 04:47 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		$blogname = wp_specialchars_decode( get_option( 'blogname' ), ENT_QUOTES );
I based this on `send_confirmation_on_profile_email()`, `update_option_new_admin_email()`, `wp_send_user_request()` and other similar functions which use this pattern. I'm really not sure why they do it that way.

2019-03-20 04:47 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +		update_site_option( 'recovery_key', array(
As opposed to? This matches the behavior of `wp_salt()`.

2019-03-20 04:48 UTC, TimothyBJacobs commented on src/wp-admin/plugins.php
> +			if ( is_multisite() && is_network_admin() ) {
We want to make sure we aren't accidentally running any code in a multisite context. It should probably be loosened to just `is_multisite()`. When we introduce multisite support, we'd remove these, but I think we want to be as safe as possible atm.

2019-03-20 04:49 UTC, TimothyBJacobs commented on src/wp-includes/admin-bar.php
> +				'title' => __( 'Exit Recovery Mode' )
Yeah, this needs exploration on the design side.

2019-03-20 04:50 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-fatal-error-handler.php
> +
That caused a compatibility issue with Query Monitor and other plugins that have their own shutdown hooks. https://core.trac.wordpress.org/ticket/46038

2019-03-20 04:52 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +				return new WP_Error( 'no_cookie' );
Good catch, fixed.

2019-03-20 04:54 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +		update_site_option( 'recovery_key', array(
Sorry, got this confused with the other comment. I'm not sure what the correct behavior is here for when we'd support multisite. Atm we could just change this to the `get_option` APIs. @felixarntz

2019-03-20 04:55 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +			$auth_salt = get_site_option( 'recovery_mode_auth_salt' );
As opposed to? This matches the behavior of wp_salt().

2019-03-20 04:55 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode.php
> +		if ( ! function_exists( 'wp_redirect' ) ) {
Updated.

2019-03-20 04:57 UTC, TimothyBJacobs commented on src/wp-includes/error-protection.php
> +	$enabled = ! defined( 'WP_DISABLE_FATAL_ERROR_HANDLER' ) || ! WP_DISABLE_FATAL_ERROR_HANDLER;
Credit goes to @felixarntz for this I believe.

2019-03-20 05:01 UTC, TimothyBJacobs commented on src/wp-includes/load.php
> +	// Protect login pages.
That's intentional. From the hook doc:

```
This filter is only fired when an endpoint is requested which is not already protected WordPress core. As such, it exclusively allows providing further protected endpoints in addition to the admin backend, login pages and protected AJAX actions.
```

And from @felixarntz original patch comments: https://core.trac.wordpress.org/ticket/44458#comment:34

2019-03-20 05:03 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +		update_site_option( 'recovery_key', array(
Going to resolve in favor of this comment since its higher on the screen :)  https://github.com/wp-core-php/wordpress-develop/pull/6#discussion_r267036435

2019-03-20 05:04 UTC, TimothyBJacobs commented on src/wp-settings.php
> +if ( ! is_multisite() ) {
Going to resolve this in favor of this comment, https://github.com/wp-core-php/wordpress-develop/pull/6#discussion_r267036435 since it appears first :)

2019-03-20 08:06 UTC, spacedmonkey commented
@TimothyBJacobs All references to *_site_option should be changed  *_option, so we can better support multisite in the future.

2019-03-20 08:10 UTC, spacedmonkey commented on src/wp-includes/load.php
> +	// Protect login pages.
Yeah, I didn't agree with that the first time around. Having conditional filter is so confusing for developers.

2019-03-20 08:13 UTC, spacedmonkey commented on src/wp-settings.php
> +wp_register_fatal_error_handler();
I think we can support that feature in multisite.

2019-03-20 10:14 UTC, felixarntz commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		if ( defined( 'WP_EXECUTION_SUCCEEDED' ) && WP_EXECUTION_SUCCEEDED ) {
Agreed. Let's continue discussion for that on the ticket though, it can go in after the first commit.

2019-03-20 10:18 UTC, felixarntz commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$paused_extensions = (array) get_option( $this->option_name, array() );
We can easily migrate to site meta when we start supporting multisite.

I also think it's best to keep the regular `get_option()` rather than including a private function from `upgrade.php`.

Registration with the REST API is something to consider, but I'd argue since the option name is based on a session ID, that would better be handled in an entirely separate controller. Furthermore it wouldn't provide significant benefits for now, it's not crucial for the feature.

2019-03-20 10:21 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		if ( ! $last_sent || time() > $last_sent + $rate_limit ) {
I agree we shouldn't use `get_site_option()` (i.e. network options) here. Switching to a transient has the problem that we can't rely on its existence though, as @TimothyBJacobs says. This is something we shouldn't consider for something as critical as a rate limit. I suggest using regular option (`get_option()` and `update_option()`).

2019-03-20 10:23 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +		update_site_option( 'recovery_key', array(
Let's refrain from using network options, and always use regular options at this point - regardless of `wp_salt()` does it. Using a network option here would potentially conflict with our solution for multisite later. Let's switch to `update_option()` / `get_option()`.

2019-03-20 10:25 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +			$auth_key = get_site_option( 'recovery_mode_auth_key' );
I think this is the only place where a network option is fine. That is because this is essentially a "bad" fallback for when the constant is not properly configured. The constant is global for an entire (multi-)site, therefore I think here we can keep using network option.

2019-03-20 10:26 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +			$auth_salt = get_site_option( 'recovery_mode_auth_salt' );
Same here, this should keep using network options since it replaces a constant (which by definition is global).

2019-03-20 10:28 UTC, felixarntz commented on src/wp-includes/load.php
> +	// Protect login pages.
It's important to ensure that developers can only add further endpoints, not remove existing ones. The way this code is written covers that.

2019-03-20 10:29 UTC, felixarntz commented
> All references to *_site_option should be changed *_option, so we can better support multisite in the future.

I agree, with the exception of those that are a fallback for a constant not being properly defined, since those are by definition global. As far as I can tell, those options would only be populated and used under these circumstances anyway.

2019-03-20 10:31 UTC, felixarntz commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		$error_types_to_handle = array(
SGTM.

2019-03-20 10:44 UTC, spacedmonkey commented on src/wp-includes/admin-bar.php
> +				'title' => __( 'Exit Recovery Mode' )
I would love it if this admin bar button was massive a red so you can't miss it.

2019-03-20 10:45 UTC, spacedmonkey commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		if ( defined( 'WP_EXECUTION_SUCCEEDED' ) && WP_EXECUTION_SUCCEEDED ) {
@felixarntz why can't we fix this now?

2019-03-20 10:45 UTC, spacedmonkey commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			if ( ! is_multisite() ) {
To be discussed

2019-03-20 10:47 UTC, spacedmonkey commented on src/wp-includes/class-wp-fatal-error-handler.php
> +		$error_types_to_handle = array(
I disagree, there maybe good you want to remove something from this list. If you want to remove something here, then that is up to you as a developer to decide.

2019-03-20 10:48 UTC, spacedmonkey commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$paused_extensions = (array) get_option( $this->option_name, array() );
Is there any worry here that the option might be filtered and mess things up?

2019-03-20 10:50 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-cookie-service.php
> +			$auth_salt = get_site_option( 'recovery_mode_auth_salt' );
If it is a constant, then it could conditional by domain.

2019-03-20 10:51 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +final class WP_Recovery_Mode_Email_Service {
Okay, I guess it can always be changed later.

2019-03-20 10:52 UTC, spacedmonkey commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		if ( ! $last_sent || time() > $last_sent + $rate_limit ) {
I am okay with `get_option`

2019-03-20 10:54 UTC, spacedmonkey commented on src/wp-includes/load.php
> +	// Protect login pages.
Okay, then the filter should run before all other logic, like other short circuits

2019-03-20 10:57 UTC, felixarntz requested changes
Looks good, now it's getting really granular with concerns. :)

I will run some testing today and tomorrow, otherwise I'd say once the outstanding feedback is addressed, this is good for commit.

2019-03-20 10:57 UTC, felixarntz commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$this->option_name = wp_recovery_mode()->get_session_id() . '_paused_extensions';
These two equal signs should be aligned, per WPCS.

2019-03-20 10:57 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +	public function maybe_send_recovery_mode_email( WP_Recovery_Mode_Link_Service $link_service, $rate_limit, $error, $extension ) {
Given that we decided against introducing a global function for the recovery link URL, I'd argue under these circumstances it _is_ better to use dependency injection with the constructor of the class, rather than individual methods. Passing instances to methods directly locks us in more than with the constructor I'd argue.
Can you move the `WP_Recovery_Mode_Link_Service` instance to a property, passed into the constructor?

Sorry about the back and forth here.

2019-03-20 10:57 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		return delete_site_option( self::RATE_LIMIT_OPTION );
This should use `delete_option()`, following our other discussion.

2019-03-20 10:57 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +			$cause = wp_sprintf( _n( 'This was caused by the %l plugin.', 'This was be caused by the %l plugins.', count( $names ) ), $names );
The clause for multiple plugins would read weird to a user. We should:
* either ditch this, only use the first name if there are multiple (I think that's perfectly fine because the rest is quite the edge-case)
* or "over-complicate" the code to ensure this is a nice comma-separated list with the last two items separated by "and"

I'd argue 1 is cleaner and covers 99% of use-cases, so I'd vote for that. But I leave the decision to you.

2019-03-20 10:57 UTC, felixarntz commented on src/wp-includes/class-wp-recovery-mode.php
> +		$this->cookies      = new WP_Recovery_Mode_Cookie_Service();
These properties should probably be named in a unified way: Either all should have a `_service` suffix, or none should have a suffix. I'd refrain from using `_handler` since the class is a service.

2019-03-20 10:57 UTC, felixarntz commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$this->option_name = wp_recovery_mode()->get_session_id() . '_paused_extensions';
I know the way the code is currently written, it can't happen, but we should cover here for the case that no session ID is available. Theoretically anyone could call `wp_paused_plugins()`/`wp_paused_themes()` at any time, potentially instantiating the class. We can't rely on the recovery mode cookie being read and the session ID being available on instantiation of this class.

To address these concerns, I suggest the following:
* We don't store the option name in a property.
* We introduce a private method `get_option_name()`:
    * It calls `wp_recovery_mode()->get_session_id()`.
    * If empty, the function returns an empty string.
    * If not empty, it returns `$session_id . '_paused_extensions'`.
* Every method that tries to access the option calls the above method. This ensures we always request the session ID when we need it rather than potentially doing it too early. Methods that use the name multiple times could store it in a variable once to make the code more readable. This shouldn't have performance implications since the session ID is elsewhere already stored in a property, so that no expensive logic needs to run.
* If the option name retrieved from the method is empty, each method should return false (or its respective default value) rather than doing anything.

2019-03-20 10:57 UTC, felixarntz commented on src/wp-settings.php
> +require( ABSPATH . WPINC . '/class-wp-recovery-mode.php' );
As mentioned, I'm okay with passing it, but we should move that to the constructor to not pollute method signatures.

2019-03-20 10:58 UTC, felixarntz commented on src/wp-settings.php
> +require( ABSPATH . WPINC . '/class-wp-recovery-mode.php' );
As mentioned, I'm okay with passing it, but we should move that to the constructor to not pollute method signatures.

2019-03-20 15:22 UTC, TimothyBJacobs commented on src/wp-settings.php
> +require( ABSPATH . WPINC . '/class-wp-recovery-mode.php' );
Will adjust.

2019-03-20 15:22 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-fatal-error-handler.php
> +			if ( ! is_multisite() ) {
Looks like we are going to keep the fatal error handler on Multisite, but not enter the recovery mode controller: https://wordpress.slack.com/archives/C60K3MP2Q/p1553074572612600

2019-03-20 15:26 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$paused_extensions = (array) get_option( $this->option_name, array() );
I'm less worried because I think the filters would only be available to `mu-plugins` or network activated plugins which we aren't pausing anyways.

2019-03-20 15:27 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		if ( ! $last_sent || time() > $last_sent + $rate_limit ) {
Updated to regular option functions.

2019-03-20 15:28 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-key-service.php
> +		update_site_option( 'recovery_key', array(
Updated.

2019-03-20 15:38 UTC, spacedmonkey commented on src/wp-admin/includes/plugin.php
> +			'Go to the Plugins screen'
Missed translation.

2019-03-20 15:38 UTC, spacedmonkey commented on src/wp-admin/includes/plugin.php
> +		sprintf(
Why is this another sprintf, this is confusing. Just use one.

2019-03-20 15:40 UTC, spacedmonkey commented on src/wp-admin/includes/theme.php
> +			'Go to the Themes screen'
Missed translation.

2019-03-20 16:03 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +		return delete_site_option( self::RATE_LIMIT_OPTION );
Updated.

2019-03-20 16:07 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +	public function maybe_send_recovery_mode_email( WP_Recovery_Mode_Link_Service $link_service, $rate_limit, $error, $extension ) {
Moved.

2019-03-20 16:08 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +			$cause = wp_sprintf( _n( 'This was caused by the %l plugin.', 'This was be caused by the %l plugins.', count( $names ) ), $names );
I think it is a comma separated list. It's using `wp_sprintf` and the `%l` format which should return a comma separated last is "and" string.

2019-03-20 16:09 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode.php
> +		$this->cookies      = new WP_Recovery_Mode_Cookie_Service();
Uses `_service` suffix.

2019-03-20 16:09 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-paused-extensions-storage.php
> +		$this->option_name = wp_recovery_mode()->get_session_id() . '_paused_extensions';
Updated.

2019-03-20 16:34 UTC, TimothyBJacobs commented on src/wp-admin/includes/plugin.php
> +			'Go to the Plugins screen'
Translated.

2019-03-20 16:34 UTC, TimothyBJacobs commented on src/wp-admin/includes/plugin.php
> +		sprintf(
Consolidated

2019-03-20 16:34 UTC, TimothyBJacobs commented on src/wp-admin/includes/theme.php
> +			'Go to the Themes screen'
Translated.

2019-03-20 16:35 UTC, TimothyBJacobs commented on src/wp-includes/admin-bar.php
> +				'title' => __( 'Exit Recovery Mode' )
Going to resolve this for now. I believe @felixarntz is involving the design team.

2019-03-20 17:11 UTC, TimothyBJacobs commented on src/wp-settings.php
> +wp_register_fatal_error_handler();
Looks like we decided to not exclude it: https://wordpress.slack.com/archives/C60K3MP2Q/p1553074572612600

2019-03-21 13:04 UTC, johnbillion commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +				'TBD',
TBD!

2019-03-21 13:05 UTC, johnbillion commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +			'subject' => __( '[%s] Your Site Experienced an Issue' ),
I'd like to see this using present tense and being more specific, eg `Your Site is Experiencing a Technical Issue`

2019-03-21 13:11 UTC, johnbillion commented on src/wp-login.php
> +				$errors->add( 'enter_recovery_mode', __( 'Recovery Mode Initialized. Please login to continue.' ), 'message' );
```suggestion
				$errors->add( 'enter_recovery_mode', __( 'Recovery Mode Initialized. Please log in to continue.' ), 'message' );
```

2019-03-21 14:45 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +				'TBD',
Is pending this issue: https://github.com/WordPress/servehappy/issues/40 :)

2019-03-21 14:47 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +			$cause = wp_sprintf( _n( 'This was caused by the %l plugin.', 'This was be caused by the %l plugins.', count( $names ) ), $names );
Yeah. It currently reads like

```
"This was be caused by the Test A and Test B plugins."
```

2019-03-21 14:51 UTC, TimothyBJacobs commented on src/wp-includes/class-wp-recovery-mode-email-service.php
> +			'subject' => __( '[%s] Your Site Experienced an Issue' ),
That sounds better to me as well, updated! Thanks!

2019-03-21 16:17 UTC, felixarntz commented
Merged against latest trunk, where the basic fatal error handler is already committed now.

2019-03-21 21:54 UTC, felixarntz commented
Done! https://core.trac.wordpress.org/changeset/44973

Thanks for this truly outstanding work @TimothyBJacobs! 🎉

2019-03-21 21:54 UTC, closed without merging

2019-03-21 22:40 UTC, TimothyBJacobs commented
Thank you! The recovery mode code wouldn't be anywhere near where it is without your extensive help.